---
title: "Untitled"
author: "Masumbuko Semba"
date: "July 7, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("E:/Data Manipulation/Kim/landuse20180328/")
rm(list = ls())
```

```{r}
require(sf)
require(tidyverse)
require(ggsci)
require(RColorBrewer)
require(gridExtra)
require(grid)
require(readxl)
require(ggsn)
```

```{r}
landuse = st_read("landuse_clean.shp")%>%select(Name, DLMC, geometry)
landuse = landuse%>%mutate(DLMC = replace(DLMC, DLMC %in% c("millitary"), "military"))
```

```{r}
points = read_excel("E:/Data Manipulation/Kim/Coordinates.xlsx")

points =  points%>%
  bind_rows(data_frame(Site = "D9", Long = 39.18, Lat = -6.794))%>%
  slice(2:9)%>%
  mutate(Site = replace(Site, Site=="D9", "D1"))%>%
  arrange(Site)

 points$Lat[6] = -6.8149717
 points = points%>%mutate(dist = oce::geodDist(points$Long, points$Lat, alongPath = TRUE))

```

 
```{r} 
river = st_read("E:/Data Manipulation/Kim/Msimbazi River/mSimbazi_river_clean.shp")
```

```{r}
metals = read_excel("E:/Data Manipulation/Kim/MetalsDataR.xlsx")%>%
  select(month = Season, As, Cd, Cr, Cu, Ni,Pb, Sn, Zn)

 metals.season = points%>%
   bind_rows(points)%>%
   bind_cols(metals)%>%
   mutate(season = month)%>%
   mutate(season = replace(season, season %in% "March", "Wet"),
          season = replace(season, season %in% "August", "Dry"))%>%
   select(c(Site, Long, Lat, dist, month, season, As, Cd, Cr, Cu, Ni,Pb, Sn, Zn))

metals.season$Site = as.factor(metals.season$Site)
metals.season$season = as.factor(metals.season$season)
#glimpse(metals.season)

metals.season.long = metals.season%>%gather(key = "metals", value = "measurements", 7:14)


```

```{r}
land.use = landuse%>%
  as_data_frame()%>%
  select(name = Name, class = DLMC)

land.use$class = as.character(land.use$class)

land.use = land.use%>%
  mutate(class = replace(class, class == "agriculture", "Agriculture"),
         class = replace(class, class == "commercial", "Commercial"),
         class = replace(class, class == "high-density residential", "High Density Residential"),
         class = replace(class, class == "industrial", "Industrial"),
         class = replace(class, class == "low-density residential", "Low Density Residential"),
         class = replace(class, class == "military", "Military"),
         class = replace(class, class == "school", "School"),
         class = replace(class, class == "transportation", "Transportation"),
         class = replace(class, class == "urban infrasture", "Urban Infrastructure"),
         class = replace(class, class == "vegetation", "Vegetation"),
         class = replace(class, class == "water", "Water"),
         class = replace(class, class == "wetland", "Wetland"))

landuse = landuse%>%bind_cols(land.use)

```



```{r}
map = ggplot()+
  geom_sf(data = landuse, aes(fill = class), col = 1)+ 
  geom_sf(data = river, col = "blue", size =1)+
  geom_point(data = points, aes(x = Long, y = Lat), size = 4, shape = 16)+
  geom_text(data = points, aes(x=Long+0.003, y = Lat+0.003, label = Site))+
  scale_fill_brewer(name = "Landuse\nlandcover\nClasses",palette = "Paired")+
  theme_bw()+
  scale_y_continuous(limits = c(-6.87, -6.765), 
                     breaks = seq(-6.86, -6.78, length.out = 3))+
  scale_x_continuous(breaks = seq(39.13, 39.3, 
                                  length.out = 3))+
  theme(legend.direction = "horizontal", 
        legend.position = c(.5,.15), 
        legend.background = element_rect(colour = 1))+
  labs(x = NULL, y = NULL)
# scale_fill_ucscgb(name = "", limits = c("agriculture", 
  #                              "industrial", 
  #                              "urban infrasture", 
  #                              "wetland", 
  #                              "water", 
  #                              "military", 
  #                              "vegetation", 
  #                              "school", 
  #                              "commercial", 
  #                              "transportation",
  #                              "low-density residential", 
  #                              "high-density residential"))+

#ggsave(filename = "landuse.jpg",dpi = 300)
north2(map, .8,.4)
scalebar(map, dist = 2, dd2km = TRUE, model = "WGS84")
```


```{r}
#read Africa continental shapefile that we will use throught the munuscript as basemap dataset for maps
africa = read_sf("E:/Data Manipulation/nyamisi/regional/africa.shp")
# clean the file
africa = africa%>%select(-c(COUNT, FIPS_CNTRY, REGIONA, EMPTY, EMPTY2))
eac = africa%>%filter(CNTRY_NAME %in% c("Tanzania", "Kenya", "Uganda"))
```



```{r}
watershed = st_read("E:/Data Manipulation/Kim/workspace4/Simbazi_watershed.shp")%>%
  st_transform(4326)
river.shed = st_read("E:/Data Manipulation/Kim/workspace4/Simbazi_river2.shp")%>%
  st_transform(4326)

ggplot()+ 
  geom_sf(data = africa, fill = "grey90", col = 1)+
  geom_sf(data = watershed, col = 1, fill = "ivory")+
  geom_sf(data = river.shed, col = "blue", show.legend = TRUE)+
  geom_point(data = points, aes(x = Long, y = Lat), size = 4, shape = 19)+
  coord_sf(xlim = c(39.0, 39.35), ylim = c(-6.98, -6.75))+
  theme_bw()+
  scale_x_continuous(breaks = seq(39.00, 39.35, length.out = 4)%>%round(digits = 2))+
  scale_y_continuous(breaks = seq(-7.0, -6.75, length.out = 5)%>%round(digits = 2))+
  labs(x = "", y = "")
 
 #  ggsave("studyarea.eps")

```

```{r}
bbox = data_frame(lon = c(39.1, 39.4, 39.4, 39.1, 39.1), lat = c(-6.9, -6.9, -6.7, -6.7, -6.9))

 ggplot()+
  geom_sf(data = eac,  fill = "grey80")+
  geom_polygon(data = bbox, aes(x = lon, y = lat), col = "red", fill  =NA, size = 0.8)+
  coord_sf(xlim = c(38.7, 40), ylim = c(-7, -5.6))+
  theme_bw()+
  scale_x_continuous(breaks = c(38.9, 39.8))+
  scale_y_continuous(breaks = c(-6.8, -5.8))+
  geom_text(aes(x = 39.8, y = -6.5, label = "Indian Ocean"),nudge_y = 0.02)+
  labs(x = "", y = "")
 
 #
 ggsave(filename = "map.eps", width = 2, height = 2)
```

```{r}
#stitch together
grid.newpage()
v1 = viewport(width = 1, height = 1, x = 0.5, y = 0.5) # plot area for the main map
#
v2 = viewport(width = 0.25, height = 0.35, x = 0.66, y = 0.35)# plot area for the inset map

print(map, vp = v1)
print(inset, vp = v2)
```


```{r}
ggplot(data = metals.season.long%>%filter(metals=="Zn"), aes(x = dist, y = measurements, col = season))+geom_line()+geom_point()
```


```{r}
ggplot(data = metals.season.long, 
       aes(x = dist, y = measurements, col = season))+
  geom_line(size = 1)+
  geom_point(size = 3)+
  facet_wrap(~metals, scales = "free_y")+
  theme_bw()+
  scale_x_continuous(breaks = seq(0,14,2))+
  labs(x = "Distance (km)", y = "Concentration (mu/L)")
#ggsave(filename = "gradient_metals.jpg")
```


```{r}
ggplot(data = metals.season.long%>%filter(metals %in% c("As", "Zn", "Cr")), 
       aes(x = dist, y = measurements, col = season))+
  geom_line(size = 1)+
  geom_point(size = 3)+
  facet_wrap(~metals, scales = "free_y")+
  theme_bw()+
  scale_x_continuous(breaks = seq(0,14,2))
```


```{r}
ggplot(data = metals.season, aes(x = As, y = Pb, col = season))+geom_point(size = 2)
```

```{r}
metals.season[,7:14]%>%plot()
cor(metals.season$As, metals.season$Pb, method = "pearson", use = "complete.obs")
# gofGroupTest(metals.season.long$measurements~metals.season.long$metals)
```

```{r}
require(factoextra)
envi = read_excel("E:/Data Manipulation/Kim/Msimbazi_Environ.xlsx")


envi.season = envi%>%rename(Temperature = `Temperature (oC)`, DO = `DO(mg/L)`, EC = `EC/(mS/s)`, ORP = `ORP/(mV)`, Turbidity = `Turbidity/(NTU)`, TDS = `TDS/(g/L)`, Salinity = `Salinity/(%)`)%>%mutate(Season = replace(Season, Season == "March", "Wet"), Season = replace(Season, Season == "August", "Dry"))

envi.season$Site = as.factor(envi.season$Site)
envi.season$Season = as.factor(envi.season$Season)

envi.metal.season = envi.season%>%bind_cols(metals)%>%select(-c(month, Longitude, latitude))%>%
  mutate(Cd = replace(Cd, is.na(Cd), 0.001), 
         Cr = replace(Cr, is.na(Cr), 0.001),
                           Cu = replace(Cu, is.na(Cu), 0.001),
                           Ni = replace(Ni, is.na(Ni), 0.001),
                           Pb = replace(Pb, is.na(Pb), 0.001),
                           Sn = replace(Sn, is.na(Sn), 0.001),
                           Zn = replace(Zn, is.na(Zn), 0.001),
                           Salinity = replace(Salinity, is.na(Salinity), 0.001))


pca = prcomp(envi.metal.season[3:18], scale. = TRUE)


fviz_pca_biplot(pca, repel = TRUE, geom = c('point', 'text'), col.ind = 'cos2',   
                habillage = envi.metal.season$Season, 
                addEllipses = TRUE, ellipse.level=0.5) + 
  theme_bw() + coord_equal()+
  theme(legend.background = element_rect(colour = 1),
        legend.position = c(.9,.85))

```


```{r}
metals.dl = as.data.frame(metals%>%select(-month)%>%as.matrix()+0.001)

envi.metal.dl.season = envi.season%>%bind_cols(metals.dl)%>%select(-c( Longitude, latitude))%>%
  mutate(Cd = replace(Cd, is.na(Cd), 0.001), 
         Cr = replace(Cr, is.na(Cr), 0.001),
                           Cu = replace(Cu, is.na(Cu), 0.001),
                           Ni = replace(Ni, is.na(Ni), 0.001),
                           Pb = replace(Pb, is.na(Pb), 0.001),
                           Sn = replace(Sn, is.na(Sn), 0.001),
                           Zn = replace(Zn, is.na(Zn), 0.001),
                           Salinity = replace(Salinity, is.na(Salinity), 0.001))


pca.dl = prcomp(envi.metal.dl.season[3:18], scale. = TRUE)


fviz_pca_biplot(pca.dl, repel = TRUE, geom = c('point', 'text'), col.ind = 'cos2',   
                habillage = envi.metal.season$Season, 
                addEllipses = TRUE, ellipse.level=0.5) + 
  theme_bw() + coord_equal()+
  theme(legend.background = element_rect(colour = 1),
        legend.position = c(.9,.85))+
  labs(title = "", x = "PC1 (30.7%)",y = "PC2 (21.9%)" )

ggsave("pca.jpg", dpi = 300)

```

